# A minimal left prompt
format = """
$directory\
$git_branch\
$git_status\
$fill\
$all\
$character"""
# add_newline = false

# move the rest of the prompt to the right
# right_format = """$all"""

[fill]
symbol = ' '

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
